import "./globals.css";
import Header from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Zoro Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
