import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Zoro Blog",
  description: "Generated by Vaibhav Rajpoot",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey="pk_test_ZXhhY3Qtc25haWwtODYuY2xlcmsuYWNjb3VudHMuZGV2JA">
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
